### PR TITLE
Convert everything to Lombok

### PR DESCRIPTION
**Pull request by boc-tothefuture**
This converts everything that was not converted in #14 and #15 into lombok.  This should make all message related object immutable and therefore threadsafe.
No rush @digitaldan since you are on holiday, take your time.

### CODE REVIEW

**Comment by boc-tothefuture** [comment]
This closes #8

**Comment by digitaldan** [comment]
Wow, that was a lot of work!  Due to the size the PR, I'm not going to be able to do a really detailed look.  That said, I do agree with the approach and my initial review looks good.  So unless you have any other objections I would like to merge this.

**Comment by boc-tothefuture** [comment]
Sounds good.  Feel free to merge it.  I will then pull it into the openhab plugin and can begin to validate functionality.

**Comment by digitaldan** [comment]
LGTM

**Pull request merged**
