### PR TITLE
Lombok properties

### PR DESCRIPTION
**Pull request by boc-tothefuture**
@digitaldan  - 
  I think we only talked about doing the status objects, but here is a PR for the properties moved to lombok as well.  Removes a lot of code and I find the builder pattern is useful and less error prone vs. the constructor method when we have so many args for a lot of the objects.  But let me know what you think.

### CODE REVIEW

**Comment by boc-tothefuture** [comment]
Hmm.. I just realized this branch also has all my status changes..  I can rebase if we need to, but for I recommend looking at #14 first and merging/discussing that, then we can inspect the properties changes in this PR.

**Comment by digitaldan** [comment]
Sounds good, I will take a look today, thanks!

**Comment by digitaldan** [comment]
So far this looks great.  I'm on holiday, trying to review on my iPad , when I get some time on my laptop I'll actually compile, test and approve.

**Comment by digitaldan** [comment]
LGTM.  Thanks, I like this method much better then the boilerplate code and useless toString methods that were there.

**Pull request merged**
