### PR TITLE
Update dependencies and manually format code

### PR DESCRIPTION
**Pull request by ecdye**
Signed-off-by: Ethan Dye <mrtops03@gmail.com>

### CODE REVIEW

**Comment by ecdye** [comment]
Force pushed to remove weird merge conflict.

**Comment by ecdye** [comment]
Note to self, next time I make changes make sure that my branch is in sync with upstream before making them. That was a pain to fix.

**Comment by digitaldan** [comment]
LGTM, thanks!!!!

**Comment by digitaldan** [comment]
do you want to bump the  pom version so we get a new release pushed to maven central ?

**Pull request merged**
